name: Playwright Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  smoke-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --ignore-optional || npm install --ignore-optional
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    
    - name: Run smoke tests
      run: npx playwright test tests/smoke-test.spec.js --project=chromium --reporter=github
      env:
        CI: true
        TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        BASE_URL: ${{ secrets.BASE_URL }}
      continue-on-error: true
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: smoke-test-report
        path: playwright-report/
        retention-days: 7
        if-no-files-found: ignore

  test-browsers:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: smoke-tests
    strategy:
      fail-fast: false  # Continue even if one browser fails
      matrix:
        browser: [chromium, firefox, webkit]
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --ignore-optional || npm install --ignore-optional
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps ${{ matrix.browser }}
    
    - name: Run Playwright tests
      run: npx playwright test --project=${{ matrix.browser }} --reporter=github
      env:
        CI: true
        TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        BASE_URL: ${{ secrets.BASE_URL }}
      continue-on-error: true  # Continue even if tests fail
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.browser }}
        path: playwright-report/
        retention-days: 30

  test-all-browsers:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    needs: smoke-tests
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --ignore-optional || npm install --ignore-optional
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Run all tests
      run: npx playwright test --reporter=html,github
      env:
        CI: true
        TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        BASE_URL: ${{ secrets.BASE_URL }}
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-all
        path: playwright-report/
        retention-days: 30
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30

  test-specific-modules:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: smoke-tests
    strategy:
      fail-fast: false  # Continue even if one module fails
      matrix:
        module: [auth, connection, dashboard, security, ui, signup, profile, errors, notifications, help]
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --ignore-optional || npm install --ignore-optional
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Run specific module tests
      run: npm run test:${{ matrix.module }}
      env:
        CI: true
        TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        BASE_URL: ${{ secrets.BASE_URL }}
      continue-on-error: true  # Continue even if tests fail
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.module }}
        path: playwright-report/
        retention-days: 7